/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application.view.memory;

/**
 *
 * @author Luism
 */
public class MemoryRegisterPanel extends javax.swing.JPanel {

    /**
     * Creates new form MemoryRegisterPanel
     */
    public MemoryRegisterPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataLB = new javax.swing.JLabel();
        addressLB = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(211, 24));
        setLayout(null);

        dataLB.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        dataLB.setText("Data");
        add(dataLB);
        dataLB.setBounds(110, 0, 100, 24);

        addressLB.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        addressLB.setText("Address");
        add(addressLB);
        addressLB.setBounds(10, 0, 100, 24);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel addressLB;
    public javax.swing.JLabel dataLB;
    // End of variables declaration//GEN-END:variables
}
