/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application.view.statistics;

import java.awt.Color;

/**
 *
 * @author Luism
 */
public class ProcessStatisticsPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessStatisticsPanel
     */
    public ProcessStatisticsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idLB = new javax.swing.JLabel();
        nameLB = new javax.swing.JLabel();
        arrivalTimeLB = new javax.swing.JLabel();
        EndTime = new javax.swing.JLabel();
        turnaroundTimeLB = new javax.swing.JLabel();
        tr_tsLB = new javax.swing.JLabel();
        colorPane = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(531, 24));
        setLayout(null);

        idLB.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        idLB.setText("ID");
        add(idLB);
        idLB.setBounds(30, 0, 30, 24);

        nameLB.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        nameLB.setText("Name");
        add(nameLB);
        nameLB.setBounds(60, 0, 90, 24);

        arrivalTimeLB.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        arrivalTimeLB.setText("Arrival time");
        add(arrivalTimeLB);
        arrivalTimeLB.setBounds(150, 0, 100, 24);

        EndTime.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        EndTime.setText("End time");
        add(EndTime);
        EndTime.setBounds(260, 0, 80, 24);

        turnaroundTimeLB.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        turnaroundTimeLB.setText("Turnaround time");
        add(turnaroundTimeLB);
        turnaroundTimeLB.setBounds(340, 0, 110, 24);

        tr_tsLB.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tr_tsLB.setText("Tr / Ts");
        add(tr_tsLB);
        tr_tsLB.setBounds(460, 0, 70, 24);

        colorPane.setBackground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout colorPaneLayout = new javax.swing.GroupLayout(colorPane);
        colorPane.setLayout(colorPaneLayout);
        colorPaneLayout.setHorizontalGroup(
            colorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        colorPaneLayout.setVerticalGroup(
            colorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        add(colorPane);
        colorPane.setBounds(6, 5, 14, 14);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel EndTime;
    public javax.swing.JLabel arrivalTimeLB;
    public javax.swing.JPanel colorPane;
    public javax.swing.JLabel idLB;
    public javax.swing.JLabel nameLB;
    public javax.swing.JLabel tr_tsLB;
    public javax.swing.JLabel turnaroundTimeLB;
    // End of variables declaration//GEN-END:variables

    public void setProcessColor(Color color) {
        this.colorPane.setBackground(color);
    }
}
