/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application.view.processlist;

/**
 *
 * @author Luism
 */
public class ProcessListPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessListPanel
     */
    public ProcessListPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        processCountLB = new javax.swing.JLabel();
        memoryManagementMethodLB = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        processListPanel = new javax.swing.JPanel();
        pcLB = new javax.swing.JLabel();
        pcLB1 = new javax.swing.JLabel();
        acLB = new javax.swing.JLabel();
        axLB = new javax.swing.JLabel();
        bxLB = new javax.swing.JLabel();
        cxLB = new javax.swing.JLabel();
        dxLB = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1040, 220));
        setLayout(null);

        jPanel1.setLayout(null);

        processCountLB.setBackground(new java.awt.Color(81, 186, 131));
        processCountLB.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        processCountLB.setForeground(new java.awt.Color(255, 255, 255));
        processCountLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        processCountLB.setText("0");
        processCountLB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        processCountLB.setOpaque(true);
        jPanel1.add(processCountLB);
        processCountLB.setBounds(962, 0, 58, 25);

        memoryManagementMethodLB.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        memoryManagementMethodLB.setForeground(new java.awt.Color(51, 51, 51));
        memoryManagementMethodLB.setText("mm");
        jPanel1.add(memoryManagementMethodLB);
        memoryManagementMethodLB.setBounds(250, 0, 210, 24);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Process List");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 5, 60, 14);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Memory managment method:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(100, 0, 140, 24);

        add(jPanel1);
        jPanel1.setBounds(10, 11, 1020, 24);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel4.setText("Name");
        add(jLabel4);
        jLabel4.setBounds(70, 40, 90, 14);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel5.setText("Status");
        add(jLabel5);
        jLabel5.setBounds(200, 40, 80, 14);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel6.setText("CPU");
        add(jLabel6);
        jLabel6.setBounds(166, 40, 30, 14);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel1.setText("ID");
        add(jLabel1);
        jLabel1.setBounds(40, 40, 30, 14);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        processListPanel.setBackground(new java.awt.Color(255, 255, 255));
        processListPanel.setLayout(new java.awt.GridLayout(20, 0, 0, 1));
        jScrollPane1.setViewportView(processListPanel);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 1020, 150);

        pcLB.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        pcLB.setText("Burst Time");
        add(pcLB);
        pcLB.setBounds(280, 40, 70, 13);

        pcLB1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        pcLB1.setText("PC");
        add(pcLB1);
        pcLB1.setBounds(360, 40, 100, 13);

        acLB.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        acLB.setText("AC");
        add(acLB);
        acLB.setBounds(470, 40, 100, 14);

        axLB.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        axLB.setText("AX");
        add(axLB);
        axLB.setBounds(580, 40, 100, 14);

        bxLB.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        bxLB.setText("BX");
        add(bxLB);
        bxLB.setBounds(690, 40, 100, 14);

        cxLB.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        cxLB.setText("CX");
        add(cxLB);
        cxLB.setBounds(800, 40, 100, 14);

        dxLB.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        dxLB.setText("DX");
        add(dxLB);
        dxLB.setBounds(910, 40, 100, 14);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel acLB;
    public javax.swing.JLabel axLB;
    public javax.swing.JLabel bxLB;
    public javax.swing.JLabel cxLB;
    public javax.swing.JLabel dxLB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel memoryManagementMethodLB;
    public javax.swing.JLabel pcLB;
    public javax.swing.JLabel pcLB1;
    public javax.swing.JLabel processCountLB;
    public javax.swing.JPanel processListPanel;
    // End of variables declaration//GEN-END:variables
}
