/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application.view;

/**
 *
 * @author Luism
 */
public class ArrivalTimeProcessPanel extends javax.swing.JPanel {

    /**
     * Creates new form ArrivalTimeProcessPanel
     */
    public ArrivalTimeProcessPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spinner = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idLB = new javax.swing.JLabel();
        nameLB = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(640, 60));
        setLayout(null);
        add(spinner);
        spinner.setBounds(90, 30, 120, 20);

        jLabel7.setText("Arrival Time:");
        jLabel7.setPreferredSize(new java.awt.Dimension(65, 24));
        add(jLabel7);
        jLabel7.setBounds(10, 30, 70, 20);

        jLabel5.setText("Process ID:");
        jLabel5.setPreferredSize(new java.awt.Dimension(65, 24));
        add(jLabel5);
        jLabel5.setBounds(10, 0, 60, 24);

        idLB.setText("-1");
        idLB.setPreferredSize(new java.awt.Dimension(65, 24));
        add(idLB);
        idLB.setBounds(70, 0, 30, 24);

        nameLB.setText("Name");
        nameLB.setPreferredSize(new java.awt.Dimension(65, 24));
        add(nameLB);
        nameLB.setBounds(180, 0, 460, 24);

        jLabel8.setText("Process Name:");
        jLabel8.setPreferredSize(new java.awt.Dimension(65, 24));
        add(jLabel8);
        jLabel8.setBounds(100, 0, 80, 24);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel idLB;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JLabel nameLB;
    public javax.swing.JSpinner spinner;
    // End of variables declaration//GEN-END:variables
}
