/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application.view;

/**
 *
 * @author Luism
 */
public class MainPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
        this.configuration.setLocationRelativeTo(this);
        this.arrivaltimeassignationpanel.setLocationRelativeTo(null);
        this.arrivaltimeassignationpanel.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        arrivaltimeassignationpanel = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        processList = new javax.swing.JPanel();
        acceptBT = new javax.swing.JButton();
        configuration = new javax.swing.JDialog();
        configurationPanel1 = new application.view.ConfigurationPanel();
        jToolBar1 = new javax.swing.JToolBar();
        loadFilesBT = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        runBT = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        settingsBT = new javax.swing.JButton();
        processListPanelParent = new application.view.processlist.ProcessListPanel();
        memoriesPanel = new application.view.memory.MemoriesPanel();
        statisticsPanel1 = new application.view.statistics.StatisticsPanel();
        displayPanel1 = new application.view.iodevices.DisplayPanel();
        processorPanel = new application.view.processor.ProcessorPanel();

        arrivaltimeassignationpanel.setTitle("Arrival time configuration");
        arrivaltimeassignationpanel.setAlwaysOnTop(true);
        arrivaltimeassignationpanel.setBackground(new java.awt.Color(255, 255, 255));
        arrivaltimeassignationpanel.setBounds(new java.awt.Rectangle(0, 0, 680, 450));
        arrivaltimeassignationpanel.setMinimumSize(new java.awt.Dimension(680, 450));
        arrivaltimeassignationpanel.setResizable(false);
        arrivaltimeassignationpanel.setSize(new java.awt.Dimension(680, 450));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setMinimumSize(new java.awt.Dimension(680, 400));
        jPanel6.setPreferredSize(new java.awt.Dimension(680, 400));
        jPanel6.setLayout(null);

        jPanel7.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Arrival time configuration");
        jLabel3.setPreferredSize(new java.awt.Dimension(65, 24));
        jPanel7.add(jLabel3);
        jLabel3.setBounds(10, 0, 280, 24);

        jPanel6.add(jPanel7);
        jPanel7.setBounds(10, 10, 660, 24);

        processList.setBackground(new java.awt.Color(255, 255, 255));
        processList.setPreferredSize(new java.awt.Dimension(620, 300));
        processList.setLayout(new java.awt.GridLayout(5, 0));
        jPanel6.add(processList);
        processList.setBounds(10, 50, 660, 300);

        acceptBT.setText("Accept");
        acceptBT.setActionCommand("accept");
        acceptBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptBTActionPerformed(evt);
            }
        });
        jPanel6.add(acceptBT);
        acceptBT.setBounds(300, 360, 80, 30);

        javax.swing.GroupLayout arrivaltimeassignationpanelLayout = new javax.swing.GroupLayout(arrivaltimeassignationpanel.getContentPane());
        arrivaltimeassignationpanel.getContentPane().setLayout(arrivaltimeassignationpanelLayout);
        arrivaltimeassignationpanelLayout.setHorizontalGroup(
            arrivaltimeassignationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        arrivaltimeassignationpanelLayout.setVerticalGroup(
            arrivaltimeassignationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        configuration.setSize(new java.awt.Dimension(680, 500));

        configurationPanel1.setPreferredSize(new java.awt.Dimension(680, 500));

        javax.swing.GroupLayout configurationLayout = new javax.swing.GroupLayout(configuration.getContentPane());
        configuration.getContentPane().setLayout(configurationLayout);
        configurationLayout.setHorizontalGroup(
            configurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(configurationPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        configurationLayout.setVerticalGroup(
            configurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(configurationPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(241, 242, 242));
        setMinimumSize(new java.awt.Dimension(1360, 730));
        setPreferredSize(new java.awt.Dimension(1360, 730));
        setLayout(null);

        jToolBar1.setBackground(new java.awt.Color(51, 51, 51));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setPreferredSize(new java.awt.Dimension(1360, 35));

        loadFilesBT.setBackground(new java.awt.Color(51, 51, 51));
        loadFilesBT.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        loadFilesBT.setForeground(new java.awt.Color(241, 242, 242));
        loadFilesBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/open.png"))); // NOI18N
        loadFilesBT.setText("Load files");
        loadFilesBT.setActionCommand("loadFiles");
        loadFilesBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loadFilesBT.setFocusable(false);
        loadFilesBT.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jToolBar1.add(loadFilesBT);
        jToolBar1.add(jSeparator1);

        runBT.setBackground(new java.awt.Color(51, 51, 51));
        runBT.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        runBT.setForeground(new java.awt.Color(241, 242, 242));
        runBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/play.png"))); // NOI18N
        runBT.setText("Run");
        runBT.setActionCommand("run");
        runBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        runBT.setEnabled(false);
        runBT.setFocusable(false);
        runBT.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jToolBar1.add(runBT);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        settingsBT.setBackground(new java.awt.Color(51, 51, 51));
        settingsBT.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        settingsBT.setForeground(new java.awt.Color(241, 242, 242));
        settingsBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/settings.png"))); // NOI18N
        settingsBT.setText("Settings");
        settingsBT.setActionCommand("settings");
        settingsBT.setContentAreaFilled(false);
        settingsBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        settingsBT.setFocusable(false);
        settingsBT.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        settingsBT.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(settingsBT);
        settingsBT.setBounds(1104, 0, 110, 35);

        jToolBar1.add(jPanel1);

        add(jToolBar1);
        jToolBar1.setBounds(0, 0, 1360, 35);
        add(processListPanelParent);
        processListPanelParent.setBounds(10, 40, 1040, 220);
        add(memoriesPanel);
        memoriesPanel.setBounds(1060, 40, 290, 460);
        add(statisticsPanel1);
        statisticsPanel1.setBounds(10, 510, 810, 210);
        add(displayPanel1);
        displayPanel1.setBounds(830, 510, 520, 210);
        add(processorPanel);
        processorPanel.setBounds(10, 270, 1040, 232);
    }// </editor-fold>//GEN-END:initComponents

    private void acceptBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acceptBTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton acceptBT;
    public javax.swing.JDialog arrivaltimeassignationpanel;
    public javax.swing.JDialog configuration;
    public application.view.ConfigurationPanel configurationPanel1;
    private application.view.iodevices.DisplayPanel displayPanel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    public javax.swing.JButton loadFilesBT;
    public application.view.memory.MemoriesPanel memoriesPanel;
    public javax.swing.JPanel processList;
    public application.view.processlist.ProcessListPanel processListPanelParent;
    public application.view.processor.ProcessorPanel processorPanel;
    public javax.swing.JButton runBT;
    public javax.swing.JButton settingsBT;
    private application.view.statistics.StatisticsPanel statisticsPanel1;
    // End of variables declaration//GEN-END:variables
}
