/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application.view.processor;

/**
 *
 * @author Luism
 */
public class ProcessorCorePanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessorCorePanel
     */
    public ProcessorCorePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        coreNumber = new javax.swing.JLabel();
        processID = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1019, 25));
        setLayout(null);

        jPanel2.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("1");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel7.setOpaque(true);
        jPanel2.add(jLabel7);
        jLabel7.setBounds(0, 0, 50, 25);

        add(jPanel2);
        jPanel2.setBounds(120, 0, 900, 25);

        coreNumber.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        coreNumber.setForeground(new java.awt.Color(51, 51, 51));
        coreNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coreNumber.setText("Core");
        coreNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        coreNumber.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        coreNumber.setOpaque(true);
        add(coreNumber);
        coreNumber.setBounds(0, 0, 60, 25);

        processID.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        processID.setForeground(new java.awt.Color(51, 51, 51));
        processID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        processID.setText("Process");
        processID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        processID.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        processID.setOpaque(true);
        add(processID);
        processID.setBounds(60, 0, 60, 25);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel coreNumber;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel processID;
    // End of variables declaration//GEN-END:variables
}
