/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application.view.processor;

/**
 *
 * @author Luism
 */
public class ProcessorCorePanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessorCorePanel
     */
    public ProcessorCorePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        executionTimesPanel = new javax.swing.JPanel();
        coreNumber = new javax.swing.JLabel();
        processID = new javax.swing.JLabel();
        irLB = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1020, 25));
        setLayout(null);

        executionTimesPanel.setLayout(null);
        add(executionTimesPanel);
        executionTimesPanel.setBounds(220, 0, 800, 25);

        coreNumber.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        coreNumber.setForeground(new java.awt.Color(51, 51, 51));
        coreNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coreNumber.setText("Core");
        coreNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        coreNumber.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        coreNumber.setOpaque(true);
        add(coreNumber);
        coreNumber.setBounds(0, 0, 60, 25);

        processID.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        processID.setForeground(new java.awt.Color(51, 51, 51));
        processID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        processID.setText("-1");
        processID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        processID.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        processID.setOpaque(true);
        add(processID);
        processID.setBounds(60, 0, 60, 25);

        irLB.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        irLB.setForeground(new java.awt.Color(51, 51, 51));
        irLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        irLB.setText("-");
        irLB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        irLB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        irLB.setOpaque(true);
        add(irLB);
        irLB.setBounds(120, 0, 100, 25);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel coreNumber;
    public javax.swing.JPanel executionTimesPanel;
    public javax.swing.JLabel irLB;
    public javax.swing.JLabel processID;
    // End of variables declaration//GEN-END:variables
}
