/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application.view.processor;

/**
 *
 * @author Luism
 */
public class TimeSecondPanel extends javax.swing.JPanel {

    /**
     * Creates new form TimeSecondPanel
     */
    public TimeSecondPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        number = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        setLayout(null);

        number.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        number.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        number.setText("0");
        number.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        number.setMaximumSize(new java.awt.Dimension(50, 25));
        number.setMinimumSize(new java.awt.Dimension(50, 25));
        number.setOpaque(true);
        number.setPreferredSize(new java.awt.Dimension(50, 25));
        add(number);
        number.setBounds(0, 0, 50, 25);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel number;
    // End of variables declaration//GEN-END:variables
}
